In [53]:
#----------------------字串練習------------------------#

#用\來轉義 (最常見的轉義序列為\n，它代表開始新的一行)
palindrome= 'a man , \naA plan \na canal: \nPanama.'
print(palindrome ,'\n','\n' ,'----')

#\t用來對齊文字(似tab功能)
print('\tabc')
print('a\tbc')
print('ab\tc')
print('abc\t', '\n','\n','----')

#用\'或\"來表示字面的單或雙引號
testimony = "\"I did nothing!\"he said. \"Not that either! or the other thing.\""
print(testimony , '\n','\n','----')

#用*來複製字串
start = 'Na ' * 4 + '\n'
middle = 'Hey ' * 3 + '\n'
end = 'Goodbye.'
print(start + start + middle + end, '\n','\n','----')

#用[]來擷取字串
letters = 'adsfsfdasdfasfsdf01275sD'
print(letters[0],letters[-1] ,'\n','\n','----')

#改變字串列
#法一：
letters = letters.replace('a', 'r')
print(letters[0],letters[-1] )
#法二：
print('p' + letters[1:],'\n','\n','----')

#使用[開始:結束:間隔]的Slice
#從位移植3到-7停止
import numpy as np
numbers = np.arange(1,20) #是自然數，不是位移值
print(numbers[3:-8])
#從開始到結束，間隔7個字元
print(numbers[::7])
#從3到結束，間隔2個字元
print(numbers[2::2],'\n','\n','----')

#使用split()來分割
todos = 'get golves, get mask, give cat vitamins, call ambulance'
todos.split(',')

#使用joint()來結合字串
crypto_list = ['Yeti', 'Bigfoot', 'Loch Ness Monster']
crypto_string = ', '.join(crypto_list)
print('Found and signing book deals:' ,crypto_string ,'\n','\n','----')

#把玩自串
#大小寫與對齊
setup = 'a duck goes into a bar...;;b;;;;'
setup = setup.strip(';')
print(setup)
#將第一個字母改為大寫
setup = setup.title()
print(setup)
#將所有字元改成大寫
setup = setup.upper()
print(setup)

#----------------------字串練習結束------------------------#


a man , 
aA plan 
a canal: 
Panama. 
 
 ----
	abc
a	bc
ab	c
abc	 
 
 ----
"I did nothing!"he said. "Not that either! or the other thing." 
 
 ----
Na Na Na Na 
Na Na Na Na 
Hey Hey Hey 
Goodbye. 
 
 ----
a D 
 
 ----
r D
pdsfsfdrsdfrsfsdf01275sD 
 
 ----
[ 4  5  6  7  8  9 10 11]
[ 1  8 15]
[ 3  5  7  9 11 13 15 17 19] 
 
 ----
Found and signing book deals: Yeti, Bigfoot, Loch Ness Monster 
 
 ----
a duck goes into a bar...;;b
A Duck Goes Into A Bar...;;B
A DUCK GOES INTO A BAR...;;B


In [63]:
#----------------------字串習題(agenda)------------------------#

#每小時有幾秒?
seconds_per_hour = 60*60
#每天有幾秒?
seconds_per_day = seconds_per_hour*60
#使用浮點數(/)除法，將前兩項相除
how_many_seconds = seconds_per_day/seconds_per_hour
print(how_many_seconds)
#使用整數除法(//)重複上述步驟
how_many_seconds = seconds_per_day//seconds_per_hour
print(how_many_seconds)

#----------------------字串習題結束(agenda)------------------------#

60.0
60
